# Unique identifier matching our Jenkinsfile variable exactly
sonar.projectKey=atm-project-banking

# Name that will be displayed on the SonarQube Dashboard UI
sonar.projectName=ATM-Project

# Application version details
sonar.projectVersion=1.0.0

# Path to the source code to be scanned (. means current directory)
sonar.sources=.

# Encoding of the source code files
sonar.sourceEncoding=UTF-8

# Language specific configuration (JavaScript for our Node.js app)
sonar.language=js

# CRITICAL SECURITY PARAMETER: Excluding configuration & infra directories.
# Inhe scan karne se avoid karenge taaki local code vulnerabilities par strict focus rahe.
sonar.exclusions=**/node_modules/**,**/k8s/**,**/terraform/**,**/ansible/**,**/.git/**,Dockerfile,Jenkinsfile
